before_install:
- sudo apt-get update -qq
#- sudo apt-get -y upgrade
- sudo apt-get install -qq groovy
- wget https://services.gradle.org/distributions/gradle-3.4.1-bin.zip
- sudo mkdir /opt/gradle
- sudo unzip -d /opt/gradle gradle-3.4.1-bin.zip
- export PATH=$PATH:/opt/gradle/gradle-3.4.1/bin
sudo: true
dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2