before_install:
- sudo apt-get update -qq
#- sudo apt-get -y upgrade
- sudo apt-get install -qq groovy
- sudo apt-get install -qq gradle
sudo: true
dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2