
server:
  context-path:  /jmsaq
  port: 8088
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

logging:
  level:
    ca.hrb: INFO
    org.springframework: ERROR
  pattern:
    console:  "%5p | %d | %F | %L | %m%n"